### ISSUE TITLE
Page directive can throw exceptions

### ISSUE THREAD

**Issue by jskeet** [hishamco/MarkdownViewEngine#2]
I'm in the habit of putting spaces in assignments, so I had

```
@page title = "Foo"
```

... at which point Substring fails. Perhaps the regex for the values should just capture the key/value pairs with regex groups? That would be simpler.

**Comment by hishamco** [comment]
Unfortunately this is a known issue before, but I think I fix it last week using `RexEx`, I think the changes that I will push may solve almost of the issues that you are reported
thanks

**Comment by hishamco** [comment]
Fixed by PR #6
