### ISSUE TITLE
Dead code in MarkdownPage

### ISSUE THREAD

**Issue by jskeet** [hishamco/MarkdownViewEngine#4]
This code in MarkdownPage does nothing useful:

```csharp
if (!String.IsNullOrEmpty(markdown))
{
    markdown.Remove(0, directiveLine.Length - 1);
}
```

I suspect the intention was `markdown = markdown.Remove(...)` but that would do the wrong thing anyway - this code should just be removed.

(Sorry for reporting it like this - I'll gear up to create pull requests soon. :)

**Comment by hishamco** [comment]
Thanks for reporting this, but there was a case previously for that, FYI this code is no longer exist in my end, hopefully today I push the latest changes, You are welcome anytime to submit a PR

**Comment by hishamco** [comment]
it's not longer exist after the commit https://github.com/hishamco/MarkdownViewEngine/commit/ac6800b4b1df8d6a9d0ed30efb6efc03193c5bb2
